# Generated by Django 6.0 on 2025-12-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование компании')),
                ('inn', models.CharField(blank=True, max_length=20, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, max_length=20, verbose_name='КПП')),
                ('ogrn', models.CharField(blank=True, max_length=20, verbose_name='ОГРН')),
                ('legal_address', models.TextField(blank=True, verbose_name='Юридический адрес')),
                ('company_phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон организации')),
                ('company_email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail организации')),
                ('director', models.CharField(blank=True, max_length=255, verbose_name='Руководитель')),
                ('bank_name', models.CharField(blank=True, max_length=255, verbose_name='Банк')),
                ('bik', models.CharField(blank=True, max_length=20, verbose_name='БИК')),
                ('correspondent_account', models.CharField(blank=True, max_length=50, verbose_name='Корр. счёт')),
                ('payment_account', models.CharField(blank=True, max_length=50, verbose_name='Расчётный счёт')),
                ('contact_person1', models.CharField(blank=True, max_length=255, verbose_name='Контактное лицо 1')),
                ('contact_phone1', models.CharField(blank=True, max_length=50, verbose_name='Телефон 1')),
                ('contact_email1', models.EmailField(blank=True, max_length=254, verbose_name='E-mail 1')),
                ('contact_person2', models.CharField(blank=True, max_length=255, verbose_name='Контактное лицо 2')),
                ('contact_phone2', models.CharField(blank=True, max_length=50, verbose_name='Телефон 2')),
                ('contact_email2', models.EmailField(blank=True, max_length=254, verbose_name='E-mail 2')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['name'],
            },
        ),
    ]
