# Generated by Django 6.0 on 2025-12-14 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.IntegerField(blank=True, help_text='Автоматическая нумерация для этого клиента', null=True, verbose_name='Номер заявки')),
                ('request_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заявки')),
                ('shipment_number', models.IntegerField(blank=True, help_text='Общая нумерация поставок компании', null=True, verbose_name='Номер поставки')),
                ('transport_type', models.CharField(choices=[('air', 'Авиа'), ('sea', 'Море'), ('rail', 'Ж/Д'), ('auto', 'Авто'), ('multimodal', 'Мультимодальная')], max_length=20, verbose_name='Основной вид транспорта')),
                ('transport_at_border', models.CharField(blank=True, choices=[('air', 'Авиа'), ('sea', 'Море'), ('rail', 'Ж/Д'), ('auto', 'Авто'), ('multimodal', 'Мультимодальная')], max_length=20, verbose_name='Вид транспорта на границе ЕАЭС')),
                ('consignor', models.TextField(verbose_name='Грузоотправитель')),
                ('consignee', models.TextField(blank=True, help_text='Если не указан, совпадает с клиентом', verbose_name='Грузополучатель')),
                ('country_of_origin', models.CharField(default='Китай', max_length=100, verbose_name='Страна происхождения груза')),
                ('gross_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Вес брутто, кг.')),
                ('volume', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Объем, м³')),
                ('declared_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Объявленная стоимость')),
                ('currency', models.CharField(choices=[('RUB', 'Рубли (RUB)'), ('USD', 'Доллары (USD)'), ('EUR', 'Евро (EUR)'), ('CNY', 'Юани (CNY)')], default='RUB', max_length=3, verbose_name='Валюта стоимости')),
                ('insurance_required', models.BooleanField(default=False, verbose_name='Требуется страхование')),
                ('special_notes', models.TextField(blank=True, verbose_name='Особые отметки')),
                ('manager', models.CharField(blank=True, max_length=100, verbose_name='Ответственный менеджер')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='clients.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Заявка на перевозку',
                'verbose_name_plural': 'Заявки на перевозку',
                'ordering': ['-request_date'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('processing', 'В обработке'), ('in_transit', 'В пути'), ('at_warehouse', 'На складе'), ('customs', 'Таможня'), ('delivered', 'Доставлено'), ('closed', 'Закрыто'), ('cancelled', 'Отменено')], default='draft', max_length=20, verbose_name='Статус поставки')),
                ('etd', models.DateField(blank=True, null=True, verbose_name='ETD (План. отправления)')),
                ('eta', models.DateField(blank=True, null=True, verbose_name='ETA (План. прибытия)')),
                ('actual_departure', models.DateField(blank=True, null=True, verbose_name='Факт. отправления')),
                ('actual_arrival', models.DateField(blank=True, null=True, verbose_name='Факт. прибытия')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Дата доставки клиенту')),
                ('document_type', models.CharField(blank=True, choices=[('awb', 'Авианакладная (AWB)'), ('bl', 'Коносамент (BL)'), ('cargo_note', 'ЖД накладная'), ('cmr', 'Дорожная накладная (CMR)'), ('tir', 'Книжка МДП (TIR)')], max_length=20, verbose_name='Тип транспортного документа')),
                ('document_number', models.CharField(blank=True, max_length=100, verbose_name='Номер транспортного документа')),
                ('carrier', models.CharField(blank=True, max_length=255, verbose_name='Перевозчик')),
                ('tracking_number', models.CharField(blank=True, max_length=100, verbose_name='Трек-номер')),
                ('customs_declaration', models.CharField(blank=True, max_length=100, verbose_name='№ ДТ/ГТД')),
                ('comments', models.TextField(blank=True, verbose_name='Комментарии менеджера')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='requests.request', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Поставка',
                'verbose_name_plural': 'Поставки',
                'ordering': ['-created_at'],
            },
        ),
    ]
